//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMediaIIoup
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.itopup.vnptepay.vn", ConfigurationName="IMediaIIoup.TopupInterface")]
    public interface TopupInterface
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signOutReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.SignOutResult> signOutAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkConnectionReturn")]
        System.Threading.Tasks.Task<string> checkConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="queryBalanceReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.BalanceResult> queryBalanceAsync(string username, string requestID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="signInAsPartnerReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.SignInResult> signInAsPartnerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkPhoneNumberReturn")]
        System.Threading.Tasks.Task<bool> checkPhoneNumberAsync(string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkTargetAccountReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.CheckTargetObject> checkTargetAccountAsync(string username, string session, string targetAcount, string providerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListCategoriesReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.CategoryListObject> partnerGetListCategoriesAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProviderOfCategoryReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.ProviderListObject> partnerGetListProviderOfCategoryAsync(string username, int categoryId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerGetListProductOfCategoryServiceProviderReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.ProductListObject> partnerGetListProductOfCategoryServiceProviderAsync(string username, int categoryId, int providerId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getListValueLevelsReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.LevelResult> getListValueLevelsAsync(string username, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getProductInformationReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.ProductInfo> getProductInformationAsync(string username, int productID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.CheckProducts[]> partnerCheckProductAsync(string username, string token, int categoryId, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerCheckProductDetailReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.CheckProductsDetail[]> partnerCheckProductDetailAsync(string username, string token, IMediaIIoup.CheckProductsDetail[] checkProducts);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="partnerChangePasswordReturn")]
        System.Threading.Tasks.Task<IMediaIIoup.ChangePasswordResult> partnerChangePasswordAsync(string username, string oldPassword, string newPassword, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProductsDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CheckProducts))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProductObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProviderObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CategoryObject))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="requestHandleReturn")]
        System.Threading.Tasks.Task<string> requestHandleAsync(string requestData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class SignOutResult
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ChangePasswordResult
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckProductsDetail
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int productIdField;
        
        private int quantityField;
        
        private bool statusField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckProducts
    {
        
        private string messageField;
        
        private int productIdField;
        
        private string productNameField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductInfo
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int productIDField;
        
        private byte[] productLogoField;
        
        private string productMessageField;
        
        private string productNameField;
        
        private int productValueField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int productID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] productLogo
        {
            get
            {
                return this.productLogoField;
            }
            set
            {
                this.productLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productMessage
        {
            get
            {
                return this.productMessageField;
            }
            set
            {
                this.productMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int productValue
        {
            get
            {
                return this.productValueField;
            }
            set
            {
                this.productValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class LevelResult
    {
        
        private int[] dataValueField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public int[] dataValue
        {
            get
            {
                return this.dataValueField;
            }
            set
            {
                this.dataValueField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductObject
    {
        
        private int productIdField;
        
        private string productNameField;
        
        private int productValueField;
        
        /// <remarks/>
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public int productValue
        {
            get
            {
                return this.productValueField;
            }
            set
            {
                this.productValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProductListObject
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private ProductObject[] productListField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ProductObject[] productList
        {
            get
            {
                return this.productListField;
            }
            set
            {
                this.productListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProviderObject
    {
        
        private string providerCodeField;
        
        private int providerIDField;
        
        private string providerNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }
        
        /// <remarks/>
        public int providerID
        {
            get
            {
                return this.providerIDField;
            }
            set
            {
                this.providerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerName
        {
            get
            {
                return this.providerNameField;
            }
            set
            {
                this.providerNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class ProviderListObject
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private ProviderObject[] providerListField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ProviderObject[] providerList
        {
            get
            {
                return this.providerListField;
            }
            set
            {
                this.providerListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CategoryObject
    {
        
        private int categoryIdField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public int categoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string categoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CategoryListObject
    {
        
        private CategoryObject[] categoryListField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public CategoryObject[] categoryList
        {
            get
            {
                return this.categoryListField;
            }
            set
            {
                this.categoryListField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class CheckTargetObject
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string providerCodeField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string providerCode
        {
            get
            {
                return this.providerCodeField;
            }
            set
            {
                this.providerCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class SignInResult
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string tokenField;
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://interfaces.itopup.vnptepay.vn")]
    public partial class BalanceResult
    {
        
        private long dataValueField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private int transIDField;
        
        /// <remarks/>
        public long dataValue
        {
            get
            {
                return this.dataValueField;
            }
            set
            {
                this.dataValueField = value;
            }
        }
        
        /// <remarks/>
        public int errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public int transID
        {
            get
            {
                return this.transIDField;
            }
            set
            {
                this.transIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TopupInterfaceChannel : IMediaIIoup.TopupInterface, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TopupInterfaceClient : System.ServiceModel.ClientBase<IMediaIIoup.TopupInterface>, IMediaIIoup.TopupInterface
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TopupInterfaceClient(string address) : 
                base(TopupInterfaceClient.GetDefaultBinding(), TopupInterfaceClient.GetDefaultEndpointAddress(address))
        {
            this.Endpoint.Name = EndpointConfiguration.TopupInterface.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TopupInterfaceClient(EndpointConfiguration endpointConfiguration,string address) : 
                base(TopupInterfaceClient.GetBindingForEndpoint(endpointConfiguration), TopupInterfaceClient.GetEndpointAddress(endpointConfiguration, address))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        //public TopupInterfaceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
        //        base(TopupInterfaceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        //{
        //    this.Endpoint.Name = endpointConfiguration.ToString();
        //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        //}
        
        public TopupInterfaceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TopupInterfaceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TopupInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.SignOutResult> signOutAsync(string username, string token)
        {
            return base.Channel.signOutAsync(username, token);
        }
        
        public System.Threading.Tasks.Task<string> checkConnectionAsync()
        {
            return base.Channel.checkConnectionAsync();
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.BalanceResult> queryBalanceAsync(string username, string requestID, string token)
        {
            return base.Channel.queryBalanceAsync(username, requestID, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.SignInResult> signInAsPartnerAsync(string username, string password)
        {
            return base.Channel.signInAsPartnerAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> checkPhoneNumberAsync(string phoneNumber)
        {
            return base.Channel.checkPhoneNumberAsync(phoneNumber);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.CheckTargetObject> checkTargetAccountAsync(string username, string session, string targetAcount, string providerCode)
        {
            return base.Channel.checkTargetAccountAsync(username, session, targetAcount, providerCode);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.CategoryListObject> partnerGetListCategoriesAsync(string username, string token)
        {
            return base.Channel.partnerGetListCategoriesAsync(username, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.ProviderListObject> partnerGetListProviderOfCategoryAsync(string username, int categoryId, string token)
        {
            return base.Channel.partnerGetListProviderOfCategoryAsync(username, categoryId, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.ProductListObject> partnerGetListProductOfCategoryServiceProviderAsync(string username, int categoryId, int providerId, string token)
        {
            return base.Channel.partnerGetListProductOfCategoryServiceProviderAsync(username, categoryId, providerId, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.LevelResult> getListValueLevelsAsync(string username, string token)
        {
            return base.Channel.getListValueLevelsAsync(username, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.ProductInfo> getProductInformationAsync(string username, int productID, string token)
        {
            return base.Channel.getProductInformationAsync(username, productID, token);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.CheckProducts[]> partnerCheckProductAsync(string username, string token, int categoryId, int providerId)
        {
            return base.Channel.partnerCheckProductAsync(username, token, categoryId, providerId);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.CheckProductsDetail[]> partnerCheckProductDetailAsync(string username, string token, IMediaIIoup.CheckProductsDetail[] checkProducts)
        {
            return base.Channel.partnerCheckProductDetailAsync(username, token, checkProducts);
        }
        
        public System.Threading.Tasks.Task<IMediaIIoup.ChangePasswordResult> partnerChangePasswordAsync(string username, string oldPassword, string newPassword, string token)
        {
            return base.Channel.partnerChangePasswordAsync(username, oldPassword, newPassword, token);
        }
        
        public System.Threading.Tasks.Task<string> requestHandleAsync(string requestData)
        {
            return base.Channel.requestHandleAsync(requestData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TopupInterface))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration,string address)
        {
            if ((endpointConfiguration == EndpointConfiguration.TopupInterface))
            {

                return new System.ServiceModel.EndpointAddress(address);
                //return new System.ServiceModel.EndpointAddress("http://103.68.241.77:8080/ItopupService1.4_IMD/services/TopupInterface");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TopupInterfaceClient.GetBindingForEndpoint(EndpointConfiguration.TopupInterface);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string address)
        {
            return TopupInterfaceClient.GetEndpointAddress(EndpointConfiguration.TopupInterface, address);
        }
        
        public enum EndpointConfiguration
        {
            
            TopupInterface,
        }
    }
}
