//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobifoneService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="UMARKETSCWS", ConfigurationName="MobifoneService.UMarketSC_PortType")]
    public interface UMarketSC_PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createsessionReturn")]
        MobifoneService.CreatesessionResponseType createsession();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createsessionReturn")]
        System.Threading.Tasks.Task<MobifoneService.CreatesessionResponseType> createsessionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="loginReturn")]
        MobifoneService.StandardBizResponse login(MobifoneService.LoginRequestType parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="loginReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> loginAsync(MobifoneService.LoginRequestType parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="balanceReturn")]
        MobifoneService.BalanceResponseType balance_all(MobifoneService.MsaleBalanceRequestType paramBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="balanceReturn")]
        System.Threading.Tasks.Task<MobifoneService.BalanceResponseType> balance_allAsync(MobifoneService.MsaleBalanceRequestType paramBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="balanceReturn")]
        MobifoneService.BalanceResponseType balance(MobifoneService.BalanceRequestType paramBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="balanceReturn")]
        System.Threading.Tasks.Task<MobifoneService.BalanceResponseType> balanceAsync(MobifoneService.BalanceRequestType paramBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyReturn")]
        MobifoneService.StandardBizResponse buy(MobifoneService.BuyRequestType paramBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buyAsync(MobifoneService.BuyRequestType paramBuy);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyAllReturn")]
        MobifoneService.StandardBizResponse buy_all(MobifoneService.MSaleBuyAllRequestType paramBuyAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyAllReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy_allAsync(MobifoneService.MSaleBuyAllRequestType paramBuyAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pinReturn")]
        MobifoneService.StandardBizResponse pin(MobifoneService.PinRequestType paramPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="pinReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> pinAsync(MobifoneService.PinRequestType paramPin);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="subscriberReturn")]
        MobifoneService.QueryBillingResponse checkSubscriber(MobifoneService.SubscriberRequestType paramCheckSubcriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="subscriberReturn")]
        System.Threading.Tasks.Task<MobifoneService.QueryBillingResponse> checkSubscriberAsync(MobifoneService.SubscriberRequestType paramCheckSubcriber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyReturn1")]
        MobifoneService.StandardBizResponse buy1(MobifoneService.BuyRequestType paramBuy1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buyReturn1")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy1Async(MobifoneService.BuyRequestType paramBuy1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resetOverFlagResponse")]
        MobifoneService.StandardBizResponse resetOverFlag(MobifoneService.ResetOverStockRequestType paramResetOverFlagRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resetOverFlagResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> resetOverFlagAsync(MobifoneService.ResetOverStockRequestType paramResetOverFlagRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="closeAllSessionResponse")]
        MobifoneService.StandardBizResponse closeAllSession(MobifoneService.CloseAllSessionRequestType paramCloseAllSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="closeAllSessionResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> closeAllSessionAsync(MobifoneService.CloseAllSessionRequestType paramCloseAllSession);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferReturn")]
        MobifoneService.StandardBizResponse transfer(MobifoneService.BuyRequestType paramTransfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transferAsync(MobifoneService.BuyRequestType paramTransfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferCReturn")]
        MobifoneService.StandardBizResponse transfer_c(MobifoneService.MsaleTransferAllRequestType paramTransferC);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferCReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transfer_cAsync(MobifoneService.MsaleTransferAllRequestType paramTransferC);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferAllReturn")]
        MobifoneService.StandardBizResponse transfer_all(MobifoneService.MsaleTransferAllRequestType paramTransferAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="transferAllReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transfer_allAsync(MobifoneService.MsaleTransferAllRequestType paramTransferAll);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkReturn")]
        MobifoneService.CheckUtTransResponseType check_trans(MobifoneService.CheckUtTransRequestType paramCheck);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkReturn")]
        System.Threading.Tasks.Task<MobifoneService.CheckUtTransResponseType> check_transAsync(MobifoneService.CheckUtTransRequestType paramCheck);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="closeReturn")]
        MobifoneService.StandardBizResponse logout(MobifoneService.StandardBizRequest paramClose);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="closeReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> logoutAsync(MobifoneService.StandardBizRequest paramClose);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resetPinReturn")]
        MobifoneService.ResetPinResponse reset_pin(MobifoneService.PinRequestType resetPinRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="resetPinReturn")]
        System.Threading.Tasks.Task<MobifoneService.ResetPinResponse> reset_pinAsync(MobifoneService.PinRequestType resetPinRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mapEzPhoneResponse")]
        MobifoneService.StandardBizResponse map_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType mapEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mapEzPhoneResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> map_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType mapEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="modifyEzPhoneResponse")]
        MobifoneService.StandardBizResponse modify_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType modifyEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="modifyEzPhoneResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> modify_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType modifyEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeEzPhoneResponse")]
        MobifoneService.StandardBizResponse remove_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType removeEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removeEzPhoneResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> remove_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType removeEzPhoneRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="m2uResponse")]
        MobifoneService.StandardBizResponse m2u(MobifoneService.M2URequestType m2uRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="m2uResponse")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> m2uAsync(MobifoneService.M2URequestType m2uRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="shareReturn")]
        MobifoneService.StandardBizResponse share_credit(MobifoneService.BuyRequestType paramShare);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="shareReturn")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> share_creditAsync(MobifoneService.BuyRequestType paramShare);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buy3Return")]
        MobifoneService.StandardBizResponse buy3(MobifoneService.BuyRequestType paramBuy3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buy3Return")]
        System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy3Async(MobifoneService.BuyRequestType paramBuy3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkSubscriberPrePaidReturn")]
        MobifoneService.CheckSubscriberPrePaidResponse checkSubscriberPrePaid(MobifoneService.SubscriberRequestType paramCheckSubscriberPrePaid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkSubscriberPrePaidReturn")]
        System.Threading.Tasks.Task<MobifoneService.CheckSubscriberPrePaidResponse> checkSubscriberPrePaidAsync(MobifoneService.SubscriberRequestType paramCheckSubscriberPrePaid);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkSubM2UReturn")]
        MobifoneService.M2UCheckSubResponseType check_sub_m2u(MobifoneService.M2UCheckSubRequestType paramCheckSubM2U);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="checkSubM2UReturn")]
        System.Threading.Tasks.Task<MobifoneService.M2UCheckSubResponseType> check_sub_m2uAsync(MobifoneService.M2UCheckSubRequestType paramCheckSubM2U);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class CreatesessionResponseType
    {
        
        private int resultField;
        
        private string result_namespaceField;
        
        private string sessionidField;
        
        /// <remarks/>
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string result_namespace
        {
            get
            {
                return this.result_namespaceField;
            }
            set
            {
                this.result_namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sessionid
        {
            get
            {
                return this.sessionidField;
            }
            set
            {
                this.sessionidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class ResetPinResponse
    {
        
        private int resultField;
        
        private string result_namespaceField;
        
        private System.Nullable<int> transidField;
        
        private string newPinField;
        
        /// <remarks/>
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string result_namespace
        {
            get
            {
                return this.result_namespaceField;
            }
            set
            {
                this.result_namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string newPin
        {
            get
            {
                return this.newPinField;
            }
            set
            {
                this.newPinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(M2UCheckSubResponseType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CheckSubscriberPrePaidResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CheckUtTransResponseType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(QueryBillingResponse))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BalanceResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class StandardBizResponse
    {
        
        private System.Nullable<decimal> feeField;
        
        private int resultField;
        
        private string result_namespaceField;
        
        private System.Nullable<long> schedule_idField;
        
        private System.Nullable<int> transidField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
        
        /// <remarks/>
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string result_namespace
        {
            get
            {
                return this.result_namespaceField;
            }
            set
            {
                this.result_namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<long> schedule_id
        {
            get
            {
                return this.schedule_idField;
            }
            set
            {
                this.schedule_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class M2UCheckSubResponseType : StandardBizResponse
    {
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class CheckSubscriberPrePaidResponse : StandardBizResponse
    {
        
        private string creditField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string credit
        {
            get
            {
                return this.creditField;
            }
            set
            {
                this.creditField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class CheckUtTransResponseType : StandardBizResponse
    {
        
        private string detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string detail
        {
            get
            {
                return this.detailField;
            }
            set
            {
                this.detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class QueryBillingResponse : StandardBizResponse
    {
        
        private double bonusAmountField;
        
        private string bonusDateField;
        
        private string debtMonthField;
        
        private double debtStaCycleField;
        
        private string msisdnField;
        
        private double paymentField;
        
        private sbyte redStatusField;
        
        private double remainingDebtField;
        
        private double usageChargeField;
        
        /// <remarks/>
        public double bonusAmount
        {
            get
            {
                return this.bonusAmountField;
            }
            set
            {
                this.bonusAmountField = value;
            }
        }
        
        /// <remarks/>
        public string bonusDate
        {
            get
            {
                return this.bonusDateField;
            }
            set
            {
                this.bonusDateField = value;
            }
        }
        
        /// <remarks/>
        public string debtMonth
        {
            get
            {
                return this.debtMonthField;
            }
            set
            {
                this.debtMonthField = value;
            }
        }
        
        /// <remarks/>
        public double debtStaCycle
        {
            get
            {
                return this.debtStaCycleField;
            }
            set
            {
                this.debtStaCycleField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public double payment
        {
            get
            {
                return this.paymentField;
            }
            set
            {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public sbyte redStatus
        {
            get
            {
                return this.redStatusField;
            }
            set
            {
                this.redStatusField = value;
            }
        }
        
        /// <remarks/>
        public double remainingDebt
        {
            get
            {
                return this.remainingDebtField;
            }
            set
            {
                this.remainingDebtField = value;
            }
        }
        
        /// <remarks/>
        public double usageCharge
        {
            get
            {
                return this.usageChargeField;
            }
            set
            {
                this.usageChargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class BalanceResponseType : StandardBizResponse
    {
        
        private System.Nullable<decimal> availField;
        
        private System.Nullable<decimal> avail_1Field;
        
        private System.Nullable<decimal> avail_2Field;
        
        private System.Nullable<decimal> avail_3Field;
        
        private System.Nullable<decimal> currentField;
        
        private System.Nullable<decimal> current_1Field;
        
        private System.Nullable<decimal> current_2Field;
        
        private System.Nullable<decimal> current_3Field;
        
        private System.Nullable<decimal> pendingField;
        
        private System.Nullable<decimal> pending_1Field;
        
        private System.Nullable<decimal> pending_2Field;
        
        private System.Nullable<decimal> pending_3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> avail
        {
            get
            {
                return this.availField;
            }
            set
            {
                this.availField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> avail_1
        {
            get
            {
                return this.avail_1Field;
            }
            set
            {
                this.avail_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> avail_2
        {
            get
            {
                return this.avail_2Field;
            }
            set
            {
                this.avail_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> avail_3
        {
            get
            {
                return this.avail_3Field;
            }
            set
            {
                this.avail_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> current_1
        {
            get
            {
                return this.current_1Field;
            }
            set
            {
                this.current_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> current_2
        {
            get
            {
                return this.current_2Field;
            }
            set
            {
                this.current_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> current_3
        {
            get
            {
                return this.current_3Field;
            }
            set
            {
                this.current_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pending
        {
            get
            {
                return this.pendingField;
            }
            set
            {
                this.pendingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pending_1
        {
            get
            {
                return this.pending_1Field;
            }
            set
            {
                this.pending_1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pending_2
        {
            get
            {
                return this.pending_2Field;
            }
            set
            {
                this.pending_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pending_3
        {
            get
            {
                return this.pending_3Field;
            }
            set
            {
                this.pending_3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(M2UCheckSubRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MSaleMapEzPhoneRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CheckUtTransRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MsaleTransferAllRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(CloseAllSessionRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ResetOverStockRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(SubscriberRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PinRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BuyRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(M2URequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MSaleBuyAllRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(BalanceRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MsaleBalanceRequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(LoginRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class StandardBizRequest
    {
        
        private string ext_couponidField;
        
        private string ext_detailsField;
        
        private string ext_sourceField;
        
        private string ext_src_methodField;
        
        private string ext_usedefaultField;
        
        private System.Nullable<int> schedfreqField;
        
        private string scheduleField;
        
        private string sessionidField;
        
        private System.Nullable<bool> suppress_confirmField;
        
        private System.Nullable<bool> suppress_notify_transField;
        
        private System.Nullable<bool> waitField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ext_couponid
        {
            get
            {
                return this.ext_couponidField;
            }
            set
            {
                this.ext_couponidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ext_details
        {
            get
            {
                return this.ext_detailsField;
            }
            set
            {
                this.ext_detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ext_source
        {
            get
            {
                return this.ext_sourceField;
            }
            set
            {
                this.ext_sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ext_src_method
        {
            get
            {
                return this.ext_src_methodField;
            }
            set
            {
                this.ext_src_methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ext_usedefault
        {
            get
            {
                return this.ext_usedefaultField;
            }
            set
            {
                this.ext_usedefaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> schedfreq
        {
            get
            {
                return this.schedfreqField;
            }
            set
            {
                this.schedfreqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string schedule
        {
            get
            {
                return this.scheduleField;
            }
            set
            {
                this.scheduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sessionid
        {
            get
            {
                return this.sessionidField;
            }
            set
            {
                this.sessionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> suppress_confirm
        {
            get
            {
                return this.suppress_confirmField;
            }
            set
            {
                this.suppress_confirmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> suppress_notify_trans
        {
            get
            {
                return this.suppress_notify_transField;
            }
            set
            {
                this.suppress_notify_transField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> wait
        {
            get
            {
                return this.waitField;
            }
            set
            {
                this.waitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class M2UCheckSubRequestType : StandardBizRequest
    {
        
        private System.Nullable<int> flagField;
        
        private string subcriberField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subcriber
        {
            get
            {
                return this.subcriberField;
            }
            set
            {
                this.subcriberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class MSaleMapEzPhoneRequestType : StandardBizRequest
    {
        
        private string fromAccoutField;
        
        private string phoneField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fromAccout
        {
            get
            {
                return this.fromAccoutField;
            }
            set
            {
                this.fromAccoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class CheckUtTransRequestType : StandardBizRequest
    {
        
        private System.Nullable<int> flagField;
        
        private string subcriberField;
        
        private string transid_requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string subcriber
        {
            get
            {
                return this.subcriberField;
            }
            set
            {
                this.subcriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transid_request
        {
            get
            {
                return this.transid_requestField;
            }
            set
            {
                this.transid_requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class MsaleTransferAllRequestType : StandardBizRequest
    {
        
        private string fromAccoutField;
        
        private string toAccoutField;
        
        private string amountField;
        
        private System.Nullable<int> typeField;
        
        private string pinField;
        
        private string messageField;
        
        private string optField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fromAccout
        {
            get
            {
                return this.fromAccoutField;
            }
            set
            {
                this.fromAccoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string toAccout
        {
            get
            {
                return this.toAccoutField;
            }
            set
            {
                this.toAccoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string opt
        {
            get
            {
                return this.optField;
            }
            set
            {
                this.optField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class CloseAllSessionRequestType : StandardBizRequest
    {
        
        private string agentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string agentName
        {
            get
            {
                return this.agentNameField;
            }
            set
            {
                this.agentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class ResetOverStockRequestType : StandardBizRequest
    {
        
        private string transidField;
        
        private string targetMSISDNField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string targetMSISDN
        {
            get
            {
                return this.targetMSISDNField;
            }
            set
            {
                this.targetMSISDNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class SubscriberRequestType : StandardBizRequest
    {
        
        private string msisdnField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string msisdn
        {
            get
            {
                return this.msisdnField;
            }
            set
            {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class PinRequestType : StandardBizRequest
    {
        
        private string initiatorField;
        
        private string new_pinField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string initiator
        {
            get
            {
                return this.initiatorField;
            }
            set
            {
                this.initiatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string new_pin
        {
            get
            {
                return this.new_pinField;
            }
            set
            {
                this.new_pinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(M2URequestType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(MSaleBuyAllRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class BuyRequestType : StandardBizRequest
    {
        
        private System.Nullable<decimal> amountField;
        
        private string notify_alternateField;
        
        private string productField;
        
        private string recipientField;
        
        private string reference1Field;
        
        private string reference2Field;
        
        private string targetField;
        
        private System.Nullable<int> typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string notify_alternate
        {
            get
            {
                return this.notify_alternateField;
            }
            set
            {
                this.notify_alternateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string product
        {
            get
            {
                return this.productField;
            }
            set
            {
                this.productField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recipient
        {
            get
            {
                return this.recipientField;
            }
            set
            {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string reference1
        {
            get
            {
                return this.reference1Field;
            }
            set
            {
                this.reference1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string reference2
        {
            get
            {
                return this.reference2Field;
            }
            set
            {
                this.reference2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class M2URequestType : BuyRequestType
    {
        
        private string source_msisdnField;
        
        private System.Nullable<decimal> feeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string source_msisdn
        {
            get
            {
                return this.source_msisdnField;
            }
            set
            {
                this.source_msisdnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class MSaleBuyAllRequestType : BuyRequestType
    {
        
        private string optField;
        
        private string phoneField;
        
        private string fromAccoutField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string opt
        {
            get
            {
                return this.optField;
            }
            set
            {
                this.optField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fromAccout
        {
            get
            {
                return this.fromAccoutField;
            }
            set
            {
                this.fromAccoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class BalanceRequestType : StandardBizRequest
    {
        
        private System.Nullable<int> typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class MsaleBalanceRequestType : StandardBizRequest
    {
        
        private System.Nullable<int> typeField;
        
        private string pinField;
        
        private string optField;
        
        private string fromAccountField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string opt
        {
            get
            {
                return this.optField;
            }
            set
            {
                this.optField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fromAccount
        {
            get
            {
                return this.fromAccountField;
            }
            set
            {
                this.fromAccountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://UMARKETSCWS")]
    public partial class LoginRequestType : StandardBizRequest
    {
        
        private string initiatorField;
        
        private string pinField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string initiator
        {
            get
            {
                return this.initiatorField;
            }
            set
            {
                this.initiatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pin
        {
            get
            {
                return this.pinField;
            }
            set
            {
                this.pinField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface UMarketSC_PortTypeChannel : MobifoneService.UMarketSC_PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class UMarketSC_PortTypeClient : System.ServiceModel.ClientBase<MobifoneService.UMarketSC_PortType>, MobifoneService.UMarketSC_PortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UMarketSC_PortTypeClient() : 
                base(UMarketSC_PortTypeClient.GetDefaultBinding(), UMarketSC_PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UMarketSC.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UMarketSC_PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(UMarketSC_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), UMarketSC_PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UMarketSC_PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UMarketSC_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UMarketSC_PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UMarketSC_PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UMarketSC_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MobifoneService.CreatesessionResponseType createsession()
        {
            return base.Channel.createsession();
        }
        
        public System.Threading.Tasks.Task<MobifoneService.CreatesessionResponseType> createsessionAsync()
        {
            return base.Channel.createsessionAsync();
        }
        
        public MobifoneService.StandardBizResponse login(MobifoneService.LoginRequestType parameters)
        {
            return base.Channel.login(parameters);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> loginAsync(MobifoneService.LoginRequestType parameters)
        {
            return base.Channel.loginAsync(parameters);
        }
        
        public MobifoneService.BalanceResponseType balance_all(MobifoneService.MsaleBalanceRequestType paramBalance)
        {
            return base.Channel.balance_all(paramBalance);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.BalanceResponseType> balance_allAsync(MobifoneService.MsaleBalanceRequestType paramBalance)
        {
            return base.Channel.balance_allAsync(paramBalance);
        }
        
        public MobifoneService.BalanceResponseType balance(MobifoneService.BalanceRequestType paramBalance)
        {
            return base.Channel.balance(paramBalance);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.BalanceResponseType> balanceAsync(MobifoneService.BalanceRequestType paramBalance)
        {
            return base.Channel.balanceAsync(paramBalance);
        }
        
        public MobifoneService.StandardBizResponse buy(MobifoneService.BuyRequestType paramBuy)
        {
            return base.Channel.buy(paramBuy);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buyAsync(MobifoneService.BuyRequestType paramBuy)
        {
            return base.Channel.buyAsync(paramBuy);
        }
        
        public MobifoneService.StandardBizResponse buy_all(MobifoneService.MSaleBuyAllRequestType paramBuyAll)
        {
            return base.Channel.buy_all(paramBuyAll);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy_allAsync(MobifoneService.MSaleBuyAllRequestType paramBuyAll)
        {
            return base.Channel.buy_allAsync(paramBuyAll);
        }
        
        public MobifoneService.StandardBizResponse pin(MobifoneService.PinRequestType paramPin)
        {
            return base.Channel.pin(paramPin);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> pinAsync(MobifoneService.PinRequestType paramPin)
        {
            return base.Channel.pinAsync(paramPin);
        }
        
        public MobifoneService.QueryBillingResponse checkSubscriber(MobifoneService.SubscriberRequestType paramCheckSubcriber)
        {
            return base.Channel.checkSubscriber(paramCheckSubcriber);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.QueryBillingResponse> checkSubscriberAsync(MobifoneService.SubscriberRequestType paramCheckSubcriber)
        {
            return base.Channel.checkSubscriberAsync(paramCheckSubcriber);
        }
        
        public MobifoneService.StandardBizResponse buy1(MobifoneService.BuyRequestType paramBuy1)
        {
            return base.Channel.buy1(paramBuy1);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy1Async(MobifoneService.BuyRequestType paramBuy1)
        {
            return base.Channel.buy1Async(paramBuy1);
        }
        
        public MobifoneService.StandardBizResponse resetOverFlag(MobifoneService.ResetOverStockRequestType paramResetOverFlagRequest)
        {
            return base.Channel.resetOverFlag(paramResetOverFlagRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> resetOverFlagAsync(MobifoneService.ResetOverStockRequestType paramResetOverFlagRequest)
        {
            return base.Channel.resetOverFlagAsync(paramResetOverFlagRequest);
        }
        
        public MobifoneService.StandardBizResponse closeAllSession(MobifoneService.CloseAllSessionRequestType paramCloseAllSession)
        {
            return base.Channel.closeAllSession(paramCloseAllSession);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> closeAllSessionAsync(MobifoneService.CloseAllSessionRequestType paramCloseAllSession)
        {
            return base.Channel.closeAllSessionAsync(paramCloseAllSession);
        }
        
        public MobifoneService.StandardBizResponse transfer(MobifoneService.BuyRequestType paramTransfer)
        {
            return base.Channel.transfer(paramTransfer);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transferAsync(MobifoneService.BuyRequestType paramTransfer)
        {
            return base.Channel.transferAsync(paramTransfer);
        }
        
        public MobifoneService.StandardBizResponse transfer_c(MobifoneService.MsaleTransferAllRequestType paramTransferC)
        {
            return base.Channel.transfer_c(paramTransferC);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transfer_cAsync(MobifoneService.MsaleTransferAllRequestType paramTransferC)
        {
            return base.Channel.transfer_cAsync(paramTransferC);
        }
        
        public MobifoneService.StandardBizResponse transfer_all(MobifoneService.MsaleTransferAllRequestType paramTransferAll)
        {
            return base.Channel.transfer_all(paramTransferAll);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> transfer_allAsync(MobifoneService.MsaleTransferAllRequestType paramTransferAll)
        {
            return base.Channel.transfer_allAsync(paramTransferAll);
        }
        
        public MobifoneService.CheckUtTransResponseType check_trans(MobifoneService.CheckUtTransRequestType paramCheck)
        {
            return base.Channel.check_trans(paramCheck);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.CheckUtTransResponseType> check_transAsync(MobifoneService.CheckUtTransRequestType paramCheck)
        {
            return base.Channel.check_transAsync(paramCheck);
        }
        
        public MobifoneService.StandardBizResponse logout(MobifoneService.StandardBizRequest paramClose)
        {
            return base.Channel.logout(paramClose);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> logoutAsync(MobifoneService.StandardBizRequest paramClose)
        {
            return base.Channel.logoutAsync(paramClose);
        }
        
        public MobifoneService.ResetPinResponse reset_pin(MobifoneService.PinRequestType resetPinRequest)
        {
            return base.Channel.reset_pin(resetPinRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.ResetPinResponse> reset_pinAsync(MobifoneService.PinRequestType resetPinRequest)
        {
            return base.Channel.reset_pinAsync(resetPinRequest);
        }
        
        public MobifoneService.StandardBizResponse map_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType mapEzPhoneRequest)
        {
            return base.Channel.map_ez_phone(mapEzPhoneRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> map_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType mapEzPhoneRequest)
        {
            return base.Channel.map_ez_phoneAsync(mapEzPhoneRequest);
        }
        
        public MobifoneService.StandardBizResponse modify_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType modifyEzPhoneRequest)
        {
            return base.Channel.modify_ez_phone(modifyEzPhoneRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> modify_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType modifyEzPhoneRequest)
        {
            return base.Channel.modify_ez_phoneAsync(modifyEzPhoneRequest);
        }
        
        public MobifoneService.StandardBizResponse remove_ez_phone(MobifoneService.MSaleMapEzPhoneRequestType removeEzPhoneRequest)
        {
            return base.Channel.remove_ez_phone(removeEzPhoneRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> remove_ez_phoneAsync(MobifoneService.MSaleMapEzPhoneRequestType removeEzPhoneRequest)
        {
            return base.Channel.remove_ez_phoneAsync(removeEzPhoneRequest);
        }
        
        public MobifoneService.StandardBizResponse m2u(MobifoneService.M2URequestType m2uRequest)
        {
            return base.Channel.m2u(m2uRequest);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> m2uAsync(MobifoneService.M2URequestType m2uRequest)
        {
            return base.Channel.m2uAsync(m2uRequest);
        }
        
        public MobifoneService.StandardBizResponse share_credit(MobifoneService.BuyRequestType paramShare)
        {
            return base.Channel.share_credit(paramShare);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> share_creditAsync(MobifoneService.BuyRequestType paramShare)
        {
            return base.Channel.share_creditAsync(paramShare);
        }
        
        public MobifoneService.StandardBizResponse buy3(MobifoneService.BuyRequestType paramBuy3)
        {
            return base.Channel.buy3(paramBuy3);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.StandardBizResponse> buy3Async(MobifoneService.BuyRequestType paramBuy3)
        {
            return base.Channel.buy3Async(paramBuy3);
        }
        
        public MobifoneService.CheckSubscriberPrePaidResponse checkSubscriberPrePaid(MobifoneService.SubscriberRequestType paramCheckSubscriberPrePaid)
        {
            return base.Channel.checkSubscriberPrePaid(paramCheckSubscriberPrePaid);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.CheckSubscriberPrePaidResponse> checkSubscriberPrePaidAsync(MobifoneService.SubscriberRequestType paramCheckSubscriberPrePaid)
        {
            return base.Channel.checkSubscriberPrePaidAsync(paramCheckSubscriberPrePaid);
        }
        
        public MobifoneService.M2UCheckSubResponseType check_sub_m2u(MobifoneService.M2UCheckSubRequestType paramCheckSubM2U)
        {
            return base.Channel.check_sub_m2u(paramCheckSubM2U);
        }
        
        public System.Threading.Tasks.Task<MobifoneService.M2UCheckSubResponseType> check_sub_m2uAsync(MobifoneService.M2UCheckSubRequestType paramCheckSubM2U)
        {
            return base.Channel.check_sub_m2uAsync(paramCheckSubM2U);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UMarketSC))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UMarketSC))
            {
                return new System.ServiceModel.EndpointAddress("http://45.121.24.20:8082/services/UMarketSC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UMarketSC_PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.UMarketSC);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UMarketSC_PortTypeClient.GetEndpointAddress(EndpointConfiguration.UMarketSC);
        }
        
        public enum EndpointConfiguration
        {
            
            UMarketSC,
        }
    }
}
