version: "3.8"

networks:
  net:
#volumes:
  #common_job_data:
services:
  common_job:
    image: hls2020/gmobile:topup_common
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://dev:123456@mongo0:27017,mongo1:27017,mongo2:27017?replicaSet=rs&readPreference=secondaryPreferred
      - ConnectionStrings__HangfireDatabaseName=topup_common_job
      - ConnectionStrings__MongoDatabaseName=topup_common

      - Kestrel__Endpoints__Http__Url=http://common:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://common:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000
      - ServiceUrlConfig__GrpcServices__Worker=http://worker:5000


      - RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=rabbitmq
      - MassTransitConfig__RabbitMqConfig__Clusters=rabbitmq
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup_job
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=123456

      - BotConfig__Url=https://api.telegram.org
      - BotConfig__BotName=gmb_bot
      - BotConfig__Token=xxx:AAF-yyy
      - BotConfig__DefaultChatId=-666888999
      
      - BotConfig__ChatIds__0__ChatId=-666888999
      - BotConfig__ChatIds__0__BotType=Dev
      
      - BotConfig__ChatIds__1__ChatId=-666888999
      - BotConfig__ChatIds__1__BotType=Sale
      
      - BotConfig__ChatIds__2__ChatId=-666888999
      - BotConfig__ChatIds__2__BotType=CardMapping
      
      - BotConfig__ChatIds__3__ChatId=-666888999
      - BotConfig__ChatIds__3__BotType=Provider
      
      - BotConfig__ChatIds__4__ChatId=-666888999
      - BotConfig__ChatIds__4__BotType=Transaction
      
      - BotConfig__ChatIds__5__ChatId=-666888999
      - BotConfig__ChatIds__5__BotType=Stock
      
      - BotConfig__ChatIds__6__ChatId=-666888999
      - BotConfig__ChatIds__6__BotType=Deposit
      
      - BotConfig__ChatIds__7__ChatId=-666888999
      - BotConfig__ChatIds__7__BotType=Channel
      
      - BotConfig__ChatIds__8__ChatId=-666888999
      - BotConfig__ChatIds__8__BotType=Private
      
      - BotConfig__ChatIds__9__ChatId=-666888999
      - BotConfig__ChatIds__9__BotType=Compare
      
      - HealthChecks__HealthChecksEnabled=true
      - HealthChecks__Url=http://common_job:80
      - HealthChecks__CheckEndpoints__IdentityServer=https://sadnbox-topup.gmobile.vn
      - HealthChecks__HealthChecksUI__HealthChecksUIEnabled=true
      - HealthChecks__HealthChecksUI__IsCheckService=true
      - HealthChecks__HealthChecksUI__EvaluationTimeOnSeconds=30
      - HealthChecks__HealthChecksUI__MinimumSecondsBetweenFailureNotifications=60
      
      - Hangfire__IsRun=true
      - Hangfire__EnableHangfire=true
      - Hangfire__ServerName=common
      - Hangfire__AutoQueryBill_IsRun=false
      - Hangfire__AutoQueryBill_IsTest=false
      - Hangfire__AutoQueryBill_CronExpressionTest=*/15 * * * *
      - Hangfire__AutoQueryBill_CronExpression=0 3 * * *
      - Hangfire__AutoQueryBill_RetryCount=3
      
      - Hangfire__AutoCheckMinBalance__IsRun=true
      - Hangfire__AutoCheckMinBalance__CronExpression=*/15 * * * *
      
      - FcmConfig__ServerUrl=https://fcm.googleapis.com
      - FcmConfig__ServerKey=xxxx
      
      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=common
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123456a@   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          #- node.labels.report!=1
      resources:
        limits:
          cpus: "1"
          memory: "1000M"
        reservations:
          memory: "500M"
    ports:
      - 9009:80
    #volumes:
      #- common_job_data:/app/Logs