version: "3.8"

networks:
  net:
#volumes:
  #common_data:
services:
  common:
    image: hls2020/gmobile:topup_common
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://topup:app_topup_2024#!&@NTN-TOPUP-MONGO01:27017,NTN-TOPUP-MONGO02:27017,NTN-TOPUP-MONGO03:27017/?replicaSet=rs0&readPreference=secondaryPreferred
      - ConnectionStrings__MongoDatabaseName=topup_common

      - Kestrel__Endpoints__Http__Url=http://common:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://stock:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000
      - ServiceUrlConfig__GrpcServices__Worker=http://worker:5000


      - RedisConfig__SentinelHosts__0=10.10.227.248:6379
      #- RedisConfig__SentinelHosts__1=10.10.227.248:6379
      #- RedisConfig__SentinelHosts__2=10.10.227.248:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=worker01
      - MassTransitConfig__RabbitMqConfig__Clusters=worker01;worker02;worker03
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=gmobile_topup2024#

      - BotConfig__Url=https://api.telegram.org
      - BotConfig__BotName=n_bot
      - BotConfig__Token=bot1475908381:AAF-6Si7FyDil2Si6pdfjHwdLF51Y3Cw_fM
      - BotConfig__DefaultChatId=-666888999
      
      - BotConfig__ChatIds__0__ChatId=-666888999
      - BotConfig__ChatIds__0__BotType=Dev
      
      - BotConfig__ChatIds__1__ChatId=-666888999
      - BotConfig__ChatIds__1__BotType=Sale
      
      - BotConfig__ChatIds__2__ChatId=-666888999
      - BotConfig__ChatIds__2__BotType=CardMapping
      
      - BotConfig__ChatIds__3__ChatId=-666888999
      - BotConfig__ChatIds__3__BotType=Provider
      
      - BotConfig__ChatIds__4__ChatId=-666888999
      - BotConfig__ChatIds__4__BotType=Transaction
      
      - BotConfig__ChatIds__5__ChatId=-666888999
      - BotConfig__ChatIds__5__BotType=Stock
      
      - BotConfig__ChatIds__6__ChatId=-666888999
      - BotConfig__ChatIds__6__BotType=Deposit
      
      - BotConfig__ChatIds__7__ChatId=-666888999
      - BotConfig__ChatIds__7__BotType=Channel
      
      - BotConfig__ChatIds__8__ChatId=-666888999
      - BotConfig__ChatIds__8__BotType=Private
      
      - BotConfig__ChatIds__9__ChatId=-666888999
      - BotConfig__ChatIds__9__BotType=Compare
      
      - HealthChecks__HealthChecksEnabled=false
      - HealthChecks__Url=http://common:80
      - HealthChecks__HealthChecksUI__HealthChecksUIEnabled=false
      - HealthChecks__HealthChecksUI__IsCheckService=false
      - HealthChecks__HealthChecksUI__EvaluationTimeOnSeconds=30
      - HealthChecks__HealthChecksUI__MinimumSecondsBetweenFailureNotifications=60
      
      - Hangfire__IsRun=false
      - Hangfire__EnableHangfire=false
      - Hangfire__ServerName=common
      - Hangfire__AutoQueryBill_IsRun=false
      - Hangfire__AutoQueryBill_IsTest=false
      - Hangfire__AutoQueryBill_CronExpressionTest=*/15 * * * *
      - Hangfire__AutoQueryBill_CronExpression=0 3 * * *
      - Hangfire__AutoQueryBill_RetryCount=3
      
      - FcmConfig__ServerUrl=https://fcm.googleapis.com
      - FcmConfig__ServerKey=AAAAAV1C7Os:APA91bEJEYZO1hlKlbuKjrgq4R58oqyF3bwHzAcK9rxRxRkjAVsId8cQSbHRUX3_p6QfWILq1dFOjEHqrx5OTU1a-EvKNebKjtF-pxrXlr2Cnobd4PCAT1ldeArKpReh1OQZbR5QIHNx
      
      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=common
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123423434a@   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.report!=1
      resources:
        limits:
          cpus: "1"
          memory: "1000M"
        reservations:
          memory: "500M"
    extra_hosts:
      - "worker01:10.10.227.228"
      - "worker02:10.10.227.229"
      - "worker03:10.10.227.230"
      - "NTN-TOPUP-MONGO01:10.10.227.245"
      - "NTN-TOPUP-MONGO02:10.10.227.246"
      - "NTN-TOPUP-MONGO03:10.10.227.247"
      - "postgres:10.10.227.248"
 
    #volumes:
      #- common_data:/app/Logs