//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayooService
{
    using System.Runtime.Serialization;
    
     
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniGWSRequest", Namespace="UniGWS")]
    public partial class UniGWSRequest : object
    {
        
        private string ClientIdField;
        
        private string RequestTimeField;
        
        private string ChecksumField;
        
        private string OperationField;
        
        private string RequestDataField;
        
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestTime
        {
            get
            {
                return this.RequestTimeField;
            }
            set
            {
                this.RequestTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Checksum
        {
            get
            {
                return this.ChecksumField;
            }
            set
            {
                this.ChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RequestData
        {
            get
            {
                return this.RequestDataField;
            }
            set
            {
                this.RequestDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniGWSResponse", Namespace="UniGWS")]
    public partial class UniGWSResponse : object
    {
        
        private string ResponseDataField;
        
        private string SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseData
        {
            get
            {
                return this.ResponseDataField;
            }
            set
            {
                this.ResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CredentialMMS", Namespace="MMS")]
    public partial class CredentialMMS : object
    {
        
        private string ClientIDField;
        
        private string ClientPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientPassword
        {
            get
            {
                return this.ClientPasswordField;
            }
            set
            {
                this.ClientPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VUGWResponse", Namespace="UniGWS")]
    public partial class VUGWResponse : object
    {
        
        private int ResponseCodeField;
        
        private string ErrorDetailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorDetail
        {
            get
            {
                return this.ErrorDetailField;
            }
            set
            {
                this.ErrorDetailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="UniGWS", ConfigurationName="PayooService.UniGWSSoap")]
    public interface UniGWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<PayooService.ExecuteResponse> ExecuteAsync(PayooService.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute2", ReplyAction="*")]
        System.Threading.Tasks.Task<PayooService.Execute2Response> Execute2Async(PayooService.Execute2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute4", ReplyAction="*")]
        System.Threading.Tasks.Task<PayooService.Execute4Response> Execute4Async(PayooService.Execute4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute5", ReplyAction="*")]
        System.Threading.Tasks.Task<PayooService.Execute5Response> Execute5Async(PayooService.Execute5Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute6", ReplyAction="*")]
        System.Threading.Tasks.Task<PayooService.Execute6Response> Execute6Async(PayooService.Execute6Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="UniGWS", Order=0)]
        public PayooService.ExecuteRequestBody Body;
        
        public ExecuteRequest()
        {
        }
        
        public ExecuteRequest(PayooService.ExecuteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class ExecuteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSRequest request;
        
        public ExecuteRequestBody()
        {
        }
        
        public ExecuteRequestBody(PayooService.UniGWSRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="UniGWS", Order=0)]
        public PayooService.ExecuteResponseBody Body;
        
        public ExecuteResponse()
        {
        }
        
        public ExecuteResponse(PayooService.ExecuteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class ExecuteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSResponse ExecuteResult;
        
        public ExecuteResponseBody()
        {
        }
        
        public ExecuteResponseBody(PayooService.UniGWSResponse ExecuteResult)
        {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2", Namespace="UniGWS", Order=0)]
        public PayooService.Execute2RequestBody Body;
        
        public Execute2Request()
        {
        }
        
        public Execute2Request(PayooService.Execute2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSRequest request;
        
        public Execute2RequestBody()
        {
        }
        
        public Execute2RequestBody(PayooService.UniGWSRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2Response", Namespace="UniGWS", Order=0)]
        public PayooService.Execute2ResponseBody Body;
        
        public Execute2Response()
        {
        }
        
        public Execute2Response(PayooService.Execute2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSResponse Execute2Result;
        
        public Execute2ResponseBody()
        {
        }
        
        public Execute2ResponseBody(PayooService.UniGWSResponse Execute2Result)
        {
            this.Execute2Result = Execute2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute4Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute4", Namespace="UniGWS", Order=0)]
        public PayooService.Execute4RequestBody Body;
        
        public Execute4Request()
        {
        }
        
        public Execute4Request(PayooService.Execute4RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute4RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string requestXML;
        
        public Execute4RequestBody()
        {
        }
        
        public Execute4RequestBody(string requestXML)
        {
            this.requestXML = requestXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute4Response", Namespace="UniGWS", Order=0)]
        public PayooService.Execute4ResponseBody Body;
        
        public Execute4Response()
        {
        }
        
        public Execute4Response(PayooService.Execute4ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute4ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Execute4Result;
        
        public Execute4ResponseBody()
        {
        }
        
        public Execute4ResponseBody(string Execute4Result)
        {
            this.Execute4Result = Execute4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute5Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute5", Namespace="UniGWS", Order=0)]
        public PayooService.Execute5RequestBody Body;
        
        public Execute5Request()
        {
        }
        
        public Execute5Request(PayooService.Execute5RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute5RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.CredentialMMS Credential;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Value;
        
        public Execute5RequestBody()
        {
        }
        
        public Execute5RequestBody(PayooService.CredentialMMS Credential, string Key, string Value)
        {
            this.Credential = Credential;
            this.Key = Key;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute5Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute5Response", Namespace="UniGWS", Order=0)]
        public PayooService.Execute5ResponseBody Body;
        
        public Execute5Response()
        {
        }
        
        public Execute5Response(PayooService.Execute5ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute5ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.VUGWResponse Execute5Result;
        
        public Execute5ResponseBody()
        {
        }
        
        public Execute5ResponseBody(PayooService.VUGWResponse Execute5Result)
        {
            this.Execute5Result = Execute5Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute6Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute6", Namespace="UniGWS", Order=0)]
        public PayooService.Execute6RequestBody Body;
        
        public Execute6Request()
        {
        }
        
        public Execute6Request(PayooService.Execute6RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute6RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSRequest request;
        
        public Execute6RequestBody()
        {
        }
        
        public Execute6RequestBody(PayooService.UniGWSRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute6Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute6Response", Namespace="UniGWS", Order=0)]
        public PayooService.Execute6ResponseBody Body;
        
        public Execute6Response()
        {
        }
        
        public Execute6Response(PayooService.Execute6ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute6ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PayooService.UniGWSResponse Execute6Result;
        
        public Execute6ResponseBody()
        {
        }
        
        public Execute6ResponseBody(PayooService.UniGWSResponse Execute6Result)
        {
            this.Execute6Result = Execute6Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface UniGWSSoapChannel : PayooService.UniGWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class UniGWSSoapClient : System.ServiceModel.ClientBase<PayooService.UniGWSSoap>, PayooService.UniGWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UniGWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UniGWSSoapClient.GetBindingForEndpoint(endpointConfiguration), UniGWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniGWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UniGWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniGWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UniGWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniGWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayooService.ExecuteResponse> PayooService.UniGWSSoap.ExecuteAsync(PayooService.ExecuteRequest request)
        {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PayooService.ExecuteResponse> ExecuteAsync(PayooService.UniGWSRequest request)
        {
            PayooService.ExecuteRequest inValue = new PayooService.ExecuteRequest();
            inValue.Body = new PayooService.ExecuteRequestBody();
            inValue.Body.request = request;
            return ((PayooService.UniGWSSoap)(this)).ExecuteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayooService.Execute2Response> PayooService.UniGWSSoap.Execute2Async(PayooService.Execute2Request request)
        {
            return base.Channel.Execute2Async(request);
        }
        
        public System.Threading.Tasks.Task<PayooService.Execute2Response> Execute2Async(PayooService.UniGWSRequest request)
        {
            PayooService.Execute2Request inValue = new PayooService.Execute2Request();
            inValue.Body = new PayooService.Execute2RequestBody();
            inValue.Body.request = request;
            return ((PayooService.UniGWSSoap)(this)).Execute2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayooService.Execute4Response> PayooService.UniGWSSoap.Execute4Async(PayooService.Execute4Request request)
        {
            return base.Channel.Execute4Async(request);
        }
        
        public System.Threading.Tasks.Task<PayooService.Execute4Response> Execute4Async(string requestXML)
        {
            PayooService.Execute4Request inValue = new PayooService.Execute4Request();
            inValue.Body = new PayooService.Execute4RequestBody();
            inValue.Body.requestXML = requestXML;
            return ((PayooService.UniGWSSoap)(this)).Execute4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayooService.Execute5Response> PayooService.UniGWSSoap.Execute5Async(PayooService.Execute5Request request)
        {
            return base.Channel.Execute5Async(request);
        }
        
        public System.Threading.Tasks.Task<PayooService.Execute5Response> Execute5Async(PayooService.CredentialMMS Credential, string Key, string Value)
        {
            PayooService.Execute5Request inValue = new PayooService.Execute5Request();
            inValue.Body = new PayooService.Execute5RequestBody();
            inValue.Body.Credential = Credential;
            inValue.Body.Key = Key;
            inValue.Body.Value = Value;
            return ((PayooService.UniGWSSoap)(this)).Execute5Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayooService.Execute6Response> PayooService.UniGWSSoap.Execute6Async(PayooService.Execute6Request request)
        {
            return base.Channel.Execute6Async(request);
        }
        
        public System.Threading.Tasks.Task<PayooService.Execute6Response> Execute6Async(PayooService.UniGWSRequest request)
        {
            PayooService.Execute6Request inValue = new PayooService.Execute6Request();
            inValue.Body = new PayooService.Execute6RequestBody();
            inValue.Body.request = request;
            return ((PayooService.UniGWSSoap)(this)).Execute6Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UniGWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UniGWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UniGWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://vusandbox.payoo.com.vn/UniGWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UniGWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://vusandbox.payoo.com.vn/UniGWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UniGWSSoap,
            
            UniGWSSoap12,
        }
    }
}
