version: "3.8"

networks:
  net:

volumes:
  topup_web_data:

secrets:
  #topup_web_appsettings:
    #file: ./app/appsettings.json
  cert_pfx:
    file: ../../ssl/gmobile.pfx

services:
  topup_web:
    image: hls2020/gmobile:topup_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      
      # Database connection strings
      - ConnectionStrings__Default=User Id=dev;Password=123456;Host=postgres;Port=5432;Database=gmobile_topup;Pooling=true;MinPoolSize=0;MaxPoolSize=200
      - ConnectionStrings__HangFire=User Id=dev;Password=123456;Host=postgres;Port=5432;Database=gmobile_topup_hangfire;Pooling=true;MinPoolSize=0;MaxPoolSize=200

      # Redis configuration
      - Abp__RedisCache__ConnectionString=redis:6379,password=123456
      - Abp__RedisCache__DatabaseId=0
      - Abp__RedisCache__RedisServer=redis://:123456@redis:6379
      - Abp__RedisCache__MasterName=mymaster

      # App settings
      - App__WebSiteRootAddress=https://sadnbox-topup.gmobile.vn/
      - App__RedirectAllowedExternalWebSites=https://localhost:44303/
      - App__SwaggerEndPoint=/swagger/v1/swagger.json
      - App__AllowHangFireServer=true
      - App__HangServerName=GMB-Web01
      - App__DownloadApp=android|ios
      - App__AppVersion=10.0.0.1
      - App__FileExtentions=.jpg,.jpeg,.gif,.png,.pdf,.dox,.docx,.xls,.xlsx,.tiff,.tif,.bmp,.BMPf,.ico,.cur,.xbm,.svg
      - App__FileKnownTypes=image/jpeg,image/png,image/gif,image/png,application/pdf,application/msword,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/svg+xml
      - App__SwichProviderConfigValue=3
      - App__ExportPerPage=5000
      - App__ApiLinkPayment=https://sandbox-api-topup.gmobile.vn
      - App__Environment=Production
      - App__EmailCCTech=admin@gmobile.vn;kythuat@gmobile.vn;letienhoang@hotmail.com
      - App__SwichLoadUserRateValue=admin;admin;supporter;supporter02
      

      # Recaptcha configuration
      - Recaptcha__SiteKey=6LfIBM8ZAAAAAPniL5hFpJZsXIPYssi-fnxre-R5
      - Recaptcha__SecretKey=6LfIBM8ZAAAAAP0IL7XQZ5FTuD73taz2jyjdWHIK

      # IdentityServer configuration
      - IdentityServer__IsEnabled=false
      - IdentityServer__Authority=https://sandbox-id.topup.gmobile.vn/
      - IdentityServer__ApiName=default-api
      - IdentityServer__ApiSecret=secret
      
      # TopupService configuration
      - TopupService__ServiceApi=http://gw_private:5000
      - TopupService__ViettelApi=https://viettel.vn
      - TopupService__TokenServer__Server=https://sandbox-topup.gmobile.vn/
      - TopupService__TokenServer__ClientId=web
      - TopupService__TokenServer__SecrectKey=def2edf7-5d42-4edc-a84a-30136c340e13
      - TopupService__TokenServer__ApiName=default-api
      - TopupService__Timeout=3000

      # CardConfig configuration
      - CardConfig__Telco=VTE,VMS,VNA
      - CardConfig__CardValues=5000,6000,10000,20000,30000,50000,100000,200000,300000,500000
      - CardConfig__EmailSendReports=hoanglt@hls.vn
      - CardConfig__BatchLotValues=TOPUP:500,PAYBILL:100,PINCODE:100-50

      # Logging configuration
      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=topup-web
      - LoggingConfig__UserName=elactic
      - LoggingConfig__Password=123456a@
      - LoggingConfig__IsDisableElk=false

      # Other configurations
      - EventBus__IsEnabled=true
      - EventBus__IsConsumer=true
      - EventBus__RabbitMq__Host=rabbitmq
      - EventBus__RabbitMq__Clusters=rabbitmq
      - EventBus__RabbitMq__VirtualHost=topup
      - EventBus__RabbitMq__Username=topup
      - EventBus__RabbitMq__Password=123456

      # KestrelServer configuration
      - KestrelServer__IsEnabled=true

      # Kestrel configuration
      - Kestrel__Endpoints__Https__Url=https://*:7000
      - Kestrel__Endpoints__Https__Certificate__Path=gmobile.vn.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=
    networks:
      - net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.70"
          memory: "2000M"
        reservations:
          memory: "500M"
    ports:
      - 6060:7000
    volumes:
      - type: volume
        source: topup_web_data
        target: /app/Logs
    secrets:
      #- source: topup_web_appsettings
        #target: /app/appsettings.Production.json
      - source: cert_pfx
        target: /app/gmobile.vn.pfx