version: "3.8"

networks:
  net:

volumes:
  backend_job_data:

services:
  backend_job:
    image: hls2020/gmobile:topup_backend
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://dev:123456@mongo0:27017,mongo1:27017,mongo2:27017?replicaSet=rs
      - ConnectionStrings__MongoDatabaseName=topup
      - ConnectionStrings__MongoHangFire=mongodb://dev:123456@mongo0:27017,mongo1:27017,mongo2:27017?replicaSet=rs&readPreference=secondaryPreferred
      - ConnectionStrings__HangfireDatabaseName=topup_backend_job

      - Kestrel__Endpoints__Http__Url=http://backend:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://backend:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000
      - ServiceUrlConfig__GrpcServices__Worker=http://worker:5000

      - RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=rabbitmq
      - MassTransitConfig__RabbitMqConfig__Clusters=rabbitmq
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup_job
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=123456

      - Hangfire__IsRun=true
      - Hangfire__EnableHangfire=true
      - Hangfire__ServcerName=BackendJob

      - Hangfire__AutoCheckTrans__IsRun=true
      - Hangfire__AutoCheckTrans__CronExpression=*/3 * * * *
      - Hangfire__AutoCheckTrans__TimeRun=2
      - Hangfire__AutoCheckTrans__IsSendTele=true  
      - Hangfire__AutoCheckTrans__IsSendTeleSlowTrans=true
      - Hangfire__AutoCheckTrans__IsSendSuccess=true  
      - Hangfire__AutoCheckTrans__IsProcess=true
      - Hangfire__AutoCheckTrans__TimePending=10

      - Hangfire__AutoCheckTrans__IsSendTeleWarning=true
      - Hangfire__AutoCheckTrans__IsSendTeleWarningSlow=true
      - Hangfire__AutoCheckTrans__MaxTransProcess=2000
      - Hangfire__AutoCheckTrans__TimePendingWarning=20
      - Hangfire__AutoCheckTrans__TimePendingWarningSlow=20      

      - Hangfire__AutoCheckTrans__IsOffset=true
      - Hangfire__AutoCheckTrans__PartnerCodeOffset=NT955771
      - Hangfire__AutoCheckTrans__RetryOffset=3

      - Hangfire__CheckLastTrans__IsRun=true
      - Hangfire__CheckLastTrans__CronExpression=*/2 * * * *
      - Hangfire__CheckLastTrans__TimeResend=15
      - Hangfire__CheckLastTrans__CountResend=5

      - Hangfire__CheckAutoCloseProvider__IsRun=true
      - Hangfire__CheckAutoCloseProvider__CronExpression=*/30 * * * * *


      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=backend_job
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123456a@    

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          #- node.labels.report!=1
      resources:
        limits:
          cpus: "1.5"
          memory: "2000M"
        reservations:
          memory: "500M"
      
    volumes:
      - backend_job_data:/app/Logs