version: "3.8"

networks:
  net:
secrets:
  cert_pfx:
    file: ../ssl/gmobile.vn.pfx
services:
  identity_server_management:
    image: hls2020/gmobile:topup_identity_admin
    networks:
      - net
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ConfigurationDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      - ConnectionStrings__PersistedGrantDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      - ConnectionStrings__IdentityDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      - ConnectionStrings__AdminLogDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      - ConnectionStrings__AdminAuditLogDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      - ConnectionStrings__DataProtectionDbConnection=Server=10.10.227.248;Port=5432;Database=identity_server_management;User Id=topup;Pwd=topup_2024#!&
      
      - SeedConfiguration__ApplySeed=false
      - DatabaseMigrationsConfiguration__ApplyDatabaseMigrations=false
      - DatabaseProviderConfiguration__ProviderType=PostgreSQL
      
      - Kestrel__Endpoints__Http__Url=http://*:5000
      - Kestrel__Endpoints__Https__Url=https://*:5001
      - Kestrel__Endpoints__Https__Certificate__Path=gmobile.vn.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=
      
      - AdminConfiguration__PageTitle=NT IdentityServer4 Admin
      - AdminConfiguration__FaviconUri=~/favicon.ico
      - AdminConfiguration__IdentityAdminRedirectUri=https://10.10.227.231:7010/signin-oidc
      - AdminConfiguration__IdentityServerBaseUrl=https://id-topup.gmobile.vn
      - AdminConfiguration__IdentityAdminCookieName=IdentityServerAdmin
      - AdminConfiguration__IdentityAdminCookieExpiresUtcHours=12
      - AdminConfiguration__RequireHttpsMetadata=false
      - AdminConfiguration__ValidateAudience=false
      - AdminConfiguration__TokenValidationClaimName=name
      - AdminConfiguration__TokenValidationClaimRole=role
      - AdminConfiguration__ClientId=gunner-sso
      - AdminConfiguration__ClientSecret=def2edf7-5d42-4edc-a84a-30136c340e13
      - AdminConfiguration__OidcResponseType=code
      #- AdminConfiguration__Scopes=openid profile email roles
      - AdminConfiguration__AdministrationRole=Admin
      - AdminConfiguration__UserRole=Admin
      - AdminConfiguration__IdentityAdminScope=identity_management
      - AdminConfiguration__HideUIForMSSqlErrorLogging=false
      - SecurityConfiguration__CspTrustedDomains[0]=fonts.googleapis.com
      - SecurityConfiguration__CspTrustedDomains[1]=fonts.gstatic.com
      - SecurityConfiguration__CspTrustedDomains[2]=www.gravatar.com
      - SmtpConfiguration__Host=
      - SmtpConfiguration__Login=
      - SmtpConfiguration__Password=
      - SendGridConfiguration__ApiKey=
      - SendGridConfiguration__SourceEmail=
      - SendGridConfiguration__SourceName=
      - AuditLoggingConfiguration__Source=IdentityServer.Admin.Web
      - AuditLoggingConfiguration__SubjectIdentifierClaim=sub
      - AuditLoggingConfiguration__SubjectNameClaim=name
      - AuditLoggingConfiguration__IncludeFormVariables=false
      - CultureConfiguration__Cultures=[]
      - CultureConfiguration__DefaultCulture=null
      - HttpConfiguration__BasePath=
      - IdentityOptions__Password__RequiredLength=8
      - IdentityOptions__User__RequireUniqueEmail=true
      - IdentityOptions__SignIn__RequireConfirmedAccount=false
      - DataProtectionConfiguration__ProtectKeysWithAzureKeyVault=false
      - AzureKeyVaultConfiguration__AzureKeyVaultEndpoint=
      - AzureKeyVaultConfiguration__ClientId=
      - AzureKeyVaultConfiguration__ClientSecret=
      - AzureKeyVaultConfiguration__TenantId=
      - AzureKeyVaultConfiguration__UseClientCredentials=true
      - AzureKeyVaultConfiguration__DataProtectionKeyIdentifier=
      - AzureKeyVaultConfiguration__ReadConfigurationFromKeyVault=false   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.report!=1
          - node.labels.job!=1
      resources:
        limits:
          cpus: "1"
          memory: "1000M"
        reservations:
          memory: "500M"
    extra_hosts:
      - "worker01:10.10.227.228"
      - "worker02:10.10.227.229"
      - "worker03:10.10.227.230"
      - "postgres:10.10.227.248"
      - "id-topup.gmobile.vn:10.10.227.248"
    ports:
      - 7010:5001          

    secrets:
      - source: cert_pfx
        target: /app/gmobile.vn.pfx
   