version: "3.8"

networks:
  net:

services:
  mobile_info:
    image: hls2020/gmobile:topup_mobileInfo
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://dev:123456@mongo0:27017,mongo1:27017,mongo2:27017?replicaSet=rs
      - ConnectionStrings__MongoDatabaseName=topup_mobile
      - ConnectionStrings__MongoDatabaseName=topup_mobile_job

      - Kestrel__Endpoints__Http__Url=http://mobile_info:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://mobile_info:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2
      
      - DaysFromLastCheck=21
      
      - Hangfire__IsRun=true
      - Hangfire__EnableHangfire=true
      - Hangfire__ServerName=MobileCheck
      - Hangfire__ProcessCategory=Checker

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000
      - ServiceUrlConfig__GrpcServices__Worker=http://worker:5000
      - ServiceUrlConfig__GatewayPrivate=http://gw_private:5000

      - RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=rabbitmq
      - MassTransitConfig__RabbitMqConfig__Clusters=rabbitmq
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=123456
      - RabbitMq__UseQueueTopup=true

      - OAuth__IdentityServer__AuthorizeUrl=https://sadnbox-topup.gmobile.vn/
      - OAuth__IdentityServer__AuthRealm=https://sadnbox-topup.gmobile.vn/
      - OAuth__IdentityServer__ClientId=web      
      - OAuth__IdentityServer__Audience=default-api            
      - OAuth__IdentityServer__ClientSecret=def2edf7-5d42-4edc-a84a-30136c340e13

      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=mobile_info
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123456a@   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          #- node.labels.report!=1
      resources:
        limits:
          cpus: "3"
          memory: "3000M"
        reservations:
          memory: "500M"
