version: "3.8"

networks:
  net:

volumes:
  gw_private_data:

services:
  gw_private:
    image: hls2020/common:api_gw
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - HostConfig__Url=http://*:5000
      - TZ=Asia/Ho_Chi_Minh
      - ApplicationOptions__IsCheckIP=false
      - ApplicationOptions__IsEnableLogging=true

      - Kestrel__IsEnable=false
      - Kestrel__Endpoints__Http__Url=http://*:5000
      #- Kestrel__Endpoints__Https__Url=https://*:5001
      #- Kestrel__Endpoints__Https__Certificate__Path=hls.vn.pfx

      - OAuth__IdentityServer__AuthorizeUrl=https://sandbox-id-topup.gmobile.vn/
      - OAuth__IdentityServer__AuthRealm=https://sandbox-id-topup.gmobile.vn/
      - OAuth__IdentityServer__ClientId=default-api      
      - OAuth__IdentityServer__Audience=default-api            
      - OAuth__IdentityServer__ClientSecret=def2edf7-5d42-4edc-a84a-30136c340e13
      - OAuth__IdentityServer__ProviderOcelotKey=def2edf7-5d42-4edc-a84a-30136c340e13

      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=gw_private
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123456a@
      - LoggingConfig__IsDisableElk=true 

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          #- node.labels.report!=1
      #resources:
        #limits:
          #cpus: "2"
          #memory: "2000M"
        #reservations:
          #memory: "500M"
    ports:
      - 8000:5000
    volumes:
      - gw_private_data:/app/Logs

      - type: bind
        source: /var/nfs_data/topup/gw_private/Configuration
        target: /app/Configuration

      #- type: bind
       # source: /var/nfs_data/topup/ssl/gmobile.vn.pfx
        #target: /app/gmobile.vn.pfx


