version: "3.8"

networks:
  net:

volumes:
  auth_data:
  
secrets:
  auth_appsettings:
    file: ./app/appsettings.json
  cert_pfx:
    file: ../ssl/gmobile.vn.pfx
services:
  auth:
    image: hls2020/gmobile:topup_web
    environment:
      - REGISTRY_CONFIG_FILE=appsettings.Production.json
      - ASPNETCORE_ENVIRONMENT=Production
      - TZ=Asia/Ho_Chi_Minh 
    networks:
      - net
    deploy:
      #mode: global
       # condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.worker01== 1
      resources:
        limits:
          cpus: "0.70"
          memory: "2000M"
        reservations:
          memory: "500M"
    ports:
      - 7004:7000
    volumes:
      - auth_data:/app/Logs
    secrets:
      - source: auth_appsettings
        target: /app/appsettings.Production.json
      - source: cert_pfx
        target: /app/gmobile.vn.pfx

