version: "3.8"

networks:
  net:
#volumes:
  #balance_data:

services:
  balance:
    image: hls2020/gmobile:topup_balance
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://dev:123456@mongo0:27017,mongo1:27017,mongo2:27017?replicaSet=rs
      - ConnectionStrings__MongoDatabaseName=topup_balance

      - Kestrel__Endpoints__Http__Url=http://balance:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://balance:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000

      - RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      #- RedisConfig__SentinelHosts__0=redis://:123456@redis:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      #- Silo__RedisCluster=redis:6379,password=123456
      #- Silo__RedisClusterDatabase=3
      #- Silo__ClusterId=balance
      #- Silo__ServiceId=balance
      #- Silo__SiloPort=11116
      #- Silo__GatewayPort=30006
      #- Silo__UseCluster=true
      
      - Silo__RedisCluster=redis:6379,password=123456
      - Silo__RedisClusterDatabase=3
      - Silo__RedisClusterPassword=123456
      - Silo__RedisStorage=redis:6379,password=123456
      - Silo__StorageDatabase=5
      - Silo__RedisStoragePassword=123456
      - Silo__RedisAuth=false
      - Silo__ClusterId=balance
      - Silo__ServiceId=balance
      - Silo__SiloPort=11116
      - Silo__GatewayPort=30006
      - Silo__UseCluster=false


      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=rabbitmq
      - MassTransitConfig__RabbitMqConfig__Clusters=rabbitmq
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=123456

      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=balance
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123456a@   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          #- node.labels.report!=1
      resources:
        limits:
          #cpus: "8"
          memory: "12000M"
        reservations:
          memory: "500M"

    ports:
      - 8081:8081
    #volumes:
      #- balance_data:/app/Logs
