version: "3.8"

networks:
  net:
#volumes:
  #balance_data:

services:
  balance:
    image: hls2020/gmobile:topup_balance
    networks:
      - net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REGISTRY_CONFIG_FILE=appsettings.json
      - TZ=Asia/Ho_Chi_Minh
      - ConnectionStrings__Mongodb=mongodb://topup:app_topup_2024#!&@NTN-TOPUP-MONGO01:27017,NTN-TOPUP-MONGO02:27017,NTN-TOPUP-MONGO03:27017/?replicaSet=rs0
      - ConnectionStrings__MongoDatabaseName=topup_balance

      - Kestrel__Endpoints__Http__Url=http://balance:80
      - Kestrel__Endpoints__Http__Protocols=Http1
      - Kestrel__Endpoints__GrpcInsecure__Url=http://balance:5000
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2

      - ServiceUrlConfig__GrpcServices__Common=http://common:5000
      - ServiceUrlConfig__GrpcServices__Backend=http://backend:5000
      - ServiceUrlConfig__GrpcServices__Report=http://report:5000
      - ServiceUrlConfig__GrpcServices__TopupGateway=http://topup_gate:5000
      - ServiceUrlConfig__GrpcServices__Commission=http://commission:5000
      - ServiceUrlConfig__GrpcServices__Balance=http://balance:5000
      - ServiceUrlConfig__GrpcServices__Stock=http://stock:5000
      - ServiceUrlConfig__GrpcServices__KppData=http://kpp_report:5000
      - ServiceUrlConfig__GrpcServices__Gateway=http://gateway:5000

      - RedisConfig__SentinelHosts__0=10.10.227.248:6379
      #- RedisConfig__SentinelHosts__1=10.10.227.248:6379
      #- RedisConfig__SentinelHosts__2=10.10.227.248:6379
      - RedisConfig__IsSentinel=false
      - RedisConfig__IsEnable=true
      - RedisConfig__MasterName=mymaster

      #- Silo__RedisCluster=10.10.227.248:6379
      #- Silo__RedisClusterDatabase=3
      #- Silo__ClusterId=balance
      #- Silo__ServiceId=balance
      #- Silo__SiloPort=11116
      #- Silo__GatewayPort=30006
      #- Silo__UseCluster=true
      
      - Silo__RedisCluster=10.10.227.248:6379
      - Silo__RedisClusterDatabase=3
      - Silo__RedisClusterPassword=123423434
      - Silo__RedisStorage=10.10.227.248:6379
      - Silo__StorageDatabase=5
      - Silo__RedisStoragePassword=123423434
      - Silo__RedisAuth=false
      - Silo__ClusterId=balance
      - Silo__ServiceId=balance
      - Silo__SiloPort=11116
      - Silo__GatewayPort=30006
      - Silo__UseCluster=true


      - MassTransitConfig__IsUseGrpc=false
      - MassTransitConfig__RabbitMqConfig__Host=worker01
      - MassTransitConfig__RabbitMqConfig__Clusters=worker01;worker02;worker03
      - MassTransitConfig__RabbitMqConfig__VirtualHost=topup
      - MassTransitConfig__RabbitMqConfig__Username=topup
      - MassTransitConfig__RabbitMqConfig__Password=gmobile_topup2024#

      - LoggingConfig__LogServer=http://elasticsearch:9200
      - LoggingConfig__LogFileUrl=Logs/logs.txt
      - LoggingConfig__OutputTemplate={Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] [{SourceContext}.{Method}] {Message}{NewLine}{Exception}
      - LoggingConfig__RollingInterval=Day
      - LoggingConfig__IndexFormat=gmb-topup-log-{0:yyyy.MM}
      - LoggingConfig__AutoRegisterTemplate=true
      - LoggingConfig__Application=balance
      - LoggingConfig__IsDisableElk=false 
      - LoggingConfig__UserName=elastic
      - LoggingConfig__Password=123423434a@   

    deploy:
      restart_policy:
        condition: on-failure
      replicas: 3
      placement:
        constraints:
          - node.role == worker
          - node.labels.report!=1
      resources:
        limits:
          #cpus: "8"
          memory: "12000M"
        reservations:
          memory: "500M"
    extra_hosts:
      - "worker01:10.10.227.228"
      - "worker02:10.10.227.229"
      - "worker03:10.10.227.230"
      - "NTN-TOPUP-MONGO01:10.10.227.245"
      - "NTN-TOPUP-MONGO02:10.10.227.246"
      - "NTN-TOPUP-MONGO03:10.10.227.247"
      - "postgres:10.10.227.248"
    ports:
      - 8081:8081
    #volumes:
      #- balance_data:/app/Logs
