name: CICD

on:
  workflow_dispatch:
    inputs:
      service:
        options:
          - all
          - backend
          - balance
          - common
          - mobile_check
          - gateway
          - report
          - stock
          - topup_gw
          - worker
          - commission
          - identity
        required: true
        type: choice
        description: Choose which service to run

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: backend
      if: ${{ github.event.inputs.service == 'backend' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_backend
      with:
        context: ./
        file: ./Topup.Backend.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_backend
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: balance
      if: ${{ github.event.inputs.service == 'balance' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_balance
      with:
        context: ./
        file: ./Topup.Balance.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_balance
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: common
      if: ${{ github.event.inputs.service == 'common' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_common
      with:
        context: ./
        file: ./Topup.Common.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_common
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: gateway
      if: ${{ github.event.inputs.service == 'gateway' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_gateway
      with:
        context: ./
        file: ./Topup.Gw.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_gateway
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: report
      if: ${{ github.event.inputs.service == 'report' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_report
      with:
        context: ./
        file: ./Topup.Report.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_report
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: topup_gw
      if: ${{ github.event.inputs.service == 'topup_gw' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_topup_gw
      with:
        context: ./
        file: ./Topup.TopupGw.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_gate
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: worker
      if: ${{ github.event.inputs.service == 'worker' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_worker
      with:
        context: ./
        file: ./Topup.Worker.Hosting/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_worker
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        
    - name: identity
      if: ${{ github.event.inputs.service == 'identity' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_identity
      with:
        context: ./
        file: ./Identity/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:topup_identity
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
